server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    data: classpath:data.sql,classpath:password-encode.sql
  security:
    oauth2:
      client:
        registration:
          messaging:
            provider: uaa
            client-id: messaging
            client-secret: secret
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/messages"
            scope: messages
            client-name: Messaging Client
        provider:
          uaa:
            authorization-uri: http://localhost:8090/uaa/oauth/authorize
            token-uri: http://localhost:8090/uaa/oauth/token
